auth:
  validity:
    accessToken: 1296000 # 3600 * 24 * 15;
    refreshToken: 1296000
  clientId: hutuplatform
  password: hutuxiaoxian
security:
  oauth2:
    client:
      access-token-validity-seconds: 1296000
      refresh-token-validity-seconds: 1296000
      client-id: hutuplatform
      client-secret: hutuxiaoxian
      authorized-grant-types: password, authorization_code,refresh_token
      client-authentication-scheme: form
    authorization:
      check-token-access: permitAll()
      token-key-access: permitAll()
authserver:
  contextPath: /account
  load-service: bj-basicdata

server:
  port: 9300
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: VcaHmg0!qBeayg$ku6f~_Q1vtalQ4egu
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: cloud-oauth
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    registry-fetch-interval-seconds: 5
